services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_local
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example_password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind
