services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    platform: linux/amd64
    ports:
      - "3000:3000"
    environment:
      MB_DB_FILE: "/metabase-data/metabase.db" # Correct mapping format
    volumes:
      - metabase_data:/metabase-data
    healthcheck:
      test: ["CMD", "curl", "--fail", "-I", "http://localhost:3000/api/health"]
      interval: 15s
      timeout: 5s
      retries: 5

volumes:
  metabase_data:
    driver: local # Stores data on the local filesystem