services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/yourpassword  # Change this to your desired password
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
    healthcheck:
      test: ["CMD-SHELL", "neo4j status"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  neo4j_data:
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/neo4j_data
  neo4j_logs:
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/neo4j_logs
  neo4j_import:
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/neo4j_import
  neo4j_plugins:
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/neo4j_plugins
