services:
  ghost:
    image: ghost:latest
    restart: always
    ports:
      - "8080:2368"
    environment:
      url: "http://localhost:8080"
      database__client: sqlite3
      database__connection__filename: "/var/lib/ghost/content/data/ghost.db"
    volumes:
      - ./ghost_data:/var/lib/ghost/content

