services:

  # Core service
  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  # Management UI
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redis_insight
    ports:
      - "8001:8001"
    depends_on:
      - redis
    environment:
      - REDISINSIGHT_HOST=0.0.0.0
      - REDISINSIGHT_PORT=8001

volumes:
  redis_data:
