# docker-compose -f docker-compose-wordpress-v1-with-local-folders.yml up -d
# docker-compose -f docker-compose-wordpress-v1-with-local-folders.yml down

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    platform: linux/amd64
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpresspassword
      WORDPRESS_DB_NAME: wordpress
      FORCE_SSL_ADMIN: False
    volumes:
      - ./wordpress_data:/var/www/html

  db:
    image: mysql:5.7
    container_name: wordpress_db
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpresspassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    platform: linux/amd64
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword

